# Generated by Django 6.0.7 on 2026-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
