import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;

class GeminiPrescriptionService {
  GeminiPrescriptionService._internal();
  static final GeminiPrescriptionService instance = GeminiPrescriptionService._internal();

  final FlutterSecureStorage _storage = const FlutterSecureStorage();
  static const String _apiKeyStorageKey = 'gemini_api_key';

  /// Retrieves the saved Gemini API key from secure storage.
  Future<String?> getApiKey() async {
    return await _storage.read(key: _apiKeyStorageKey);
  }

  /// Saves a user-provided Gemini API key to secure storage.
  Future<void> setApiKey(String key) async {
    await _storage.write(key: _apiKeyStorageKey, value: key.trim());
  }

  /// Sends a prescription photo to the Google Gemini API to extract medicine names.
  /// Returns a list of extracted medicine names.
  Future<List<String>> analyzePrescriptionImage(
    Uint8List imageBytes, {
    String mimeType = 'image/jpeg',
    String? overrideApiKey,
  }) async {
    final apiKey = overrideApiKey ?? await getApiKey();
    if (apiKey == null || apiKey.trim().isEmpty) {
      throw Exception('Gemini API key is required. Please set your API key first.');
    }

    final base64Image = base64Encode(imageBytes);

    // Endpoint for Gemini 1.5 Flash (free tier supported)
    final url = Uri.parse(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=$apiKey',
    );

    final requestBody = jsonEncode({
      'contents': [
        {
          'parts': [
            {
              'text':
                  'You are a medical OCR scanner. Analyze this prescription photo and extract only the names of the prescribed medicines/medications. Return ONLY a comma-separated list of the medicine names (e.g. Amoxicillin, Paracetamol, Metformin). Do not include any explanations, bullet points, numbering, or preamble.',
            },
            {
              'inline_data': {
                'mime_type': mimeType,
                'data': base64Image,
              },
            },
          ],
        },
      ],
    });

    final response = await http.post(
      url,
      headers: {'Content-Type': 'application/json'},
      body: requestBody,
    );

    if (response.statusCode != 200) {
      String errorMessage = 'Failed to analyze image (HTTP ${response.statusCode})';
      try {
        final errJson = jsonDecode(response.body);
        if (errJson is Map && errJson.containsKey('error') && errJson['error'] is Map) {
          errorMessage = errJson['error']['message'] ?? errorMessage;
        }
      } catch (_) {}
      throw Exception(errorMessage);
    }

    final responseJson = jsonDecode(response.body) as Map<String, dynamic>;
    final candidates = responseJson['candidates'] as List?;
    if (candidates == null || candidates.isEmpty) {
      throw Exception('No response generated by Gemini API.');
    }

    final firstCandidate = candidates.first as Map<String, dynamic>;
    final content = firstCandidate['content'] as Map<String, dynamic>?;
    final parts = content?['parts'] as List?;
    if (parts == null || parts.isEmpty) {
      throw Exception('Could not extract text from Gemini response.');
    }

    final rawText = parts.first['text'] as String? ?? '';
    
    // Parse medicine names from comma/newline separated text
    final medicineNames = rawText
        .split(RegExp(r'[,;\n]'))
        .map((name) => name.replaceAll(RegExp(r'^[\d\.\*\-\s]+'), '').trim())
        .where((name) => name.isNotEmpty)
        .toList();

    return medicineNames;
  }
}
