"""
Django settings for medalert_api project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-#-4iijzk*&b_fuj%21q%l6tmrcnm2tn_3@kehex05i2&b6_r6-',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Must include the address phones actually type. A device hitting
# http://192.168.1.64:8000 sends "Host: 192.168.1.64:8000", and Django rejects
# any host not listed here with 400 DisallowedHost -- which looks exactly like
# a dead server from the app's side. The default below only covers the
# development machine itself, so set ALLOWED_HOSTS in .env to your LAN IP
# before testing on real devices.
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost,10.0.2.2,0.0.0.0',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)


# Application definition


INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',

        # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',

    # Local apps
    'core',
    'pharmacy',
    'emergency',
    'sync',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medalert_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medalert_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME', default='medalert_api'),
        'USER': config('DATABASE_USER', default='postgres'),
        'PASSWORD': config('DATABASE_PASSWORD', default=''),
        'HOST': config('DATABASE_HOST', default='localhost'),
        'PORT': config('DATABASE_PORT', default='5432'),
        # PostgreSQL has real row-level locking, so select_for_update() in
        # pharmacy/services.py's apply_stock_change() genuinely serialises
        # concurrent writers on the same stock row here (unlike SQLite, where
        # it's a documented no-op). Do not remove select_for_update() -- see
        # the note on test_concurrent_requests_do_not_lose_updates in the
        # README/tests.
        'CONN_MAX_AGE': config('DATABASE_CONN_MAX_AGE', default=60, cast=int),
    }
}

# Channels / WebSocket config for C2 real-time stock sync
ASGI_APPLICATION = 'medalert_api.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        # SINGLE PROCESS ONLY. InMemoryChannelLayer keeps groups in the
        # process's own memory, so a stock alert published by one worker is
        # invisible to clients connected to any other worker. That is fine for
        # `manage.py runserver` (one process), which is how the demo runs, and
        # it means several phones watching the same pharmacy all receive
        # updates.
        #
        # Do NOT start multiple workers (e.g. `daphne -w 4`, or gunicorn with
        # >1 worker) against this backend: real-time updates will reach only
        # the subset of phones that happened to land on the publishing worker,
        # and it will look like flaky wifi rather than a config error.
        #
        # To scale beyond one process, switch to the Redis layer below --
        # channels-redis is already in requirements.txt.
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    # Only views that set throttle_scope are limited; everything else stays
    # unthrottled. The unauthenticated endpoints are the ones worth covering:
    # login and register are password-guessing surfaces, and the share endpoint
    # serves medical data to anyone holding the URL, so an unlimited endpoint
    # there lets someone walk the token space at whatever rate they like.
    #
    # Rates are deliberately loose. These exist to make brute force
    # impractical, not to police normal use -- a demo where several people log
    # in and out on the same wifi (one NAT'd IP, so DRF sees them as one
    # client) must never hit a limit.
    'DEFAULT_THROTTLE_RATES': {
        'login': '20/min',
        'register': '10/min',
        'shared_profile': '30/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'MedAlert API',
    'DESCRIPTION': 'API for pharmacy, medicine, and emergency alert data for the MedAlert app.',
    'VERSION': '1.0.0',
}

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS',
        default='',
        cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
    )