import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';
import '../state.dart';
import '../widgets/emergency_call.dart';
import '../widgets/initials_avatar.dart';

class MedicalIdScreen extends StatefulWidget {
  const MedicalIdScreen({super.key});

  @override
  State<MedicalIdScreen> createState() => _MedicalIdScreenState();
}

class _MedicalIdScreenState extends State<MedicalIdScreen> {
  final GlobalKey _qrBoundaryKey = GlobalKey();
  bool _isDownloading = false;

  String _buildEmergencyPayload(UserProfile profile) {
    final buffer = StringBuffer()
      ..writeln('MEDALERT EMERGENCY MEDICAL ID')
      ..writeln('--------------------------------');

    if (profile.medicalId.isNotEmpty) {
      buffer.writeln('Medical ID: ${profile.medicalId}');
    }

    buffer
      ..writeln('Name: ${profile.fullName}')
      ..writeln(
        'Gender: ${profile.gender.isNotEmpty ? profile.gender : 'Not specified'}',
      )
      ..writeln('DOB: ${profile.dob}')
      ..writeln(
        'Phone: ${profile.phoneNumber.isNotEmpty ? profile.phoneNumber : 'Not specified'}',
      )
      ..writeln(
        'Blood Group: ${profile.bloodGroup.isNotEmpty ? profile.bloodGroup : 'Not specified'}',
      );

    if (profile.height.trim().isNotEmpty) {
      buffer.writeln('Height: ${profile.height} cm');
    }
    if (profile.weight.trim().isNotEmpty) {
      buffer.writeln('Weight: ${profile.weight} kg');
    }
    if (profile.address.trim().isNotEmpty) {
      buffer.writeln('Address: ${profile.address}');
    }

    buffer.writeln(
      'SEVERE ALLERGIES: ${profile.allergies.isEmpty ? 'None reported' : profile.allergies.join(', ')}',
    );

    if (profile.medications.isNotEmpty) {
      final meds = profile.medications
          .map((m) => '${m.name} ${m.dosage} (${m.frequency})')
          .join('; ');
      buffer.writeln('Medications: $meds');
    }

    if (profile.emergencyContacts.isNotEmpty) {
      buffer.writeln('--------------------------------');
      buffer.writeln('Emergency Contacts:');
      for (final contact in profile.emergencyContacts) {
        buffer.writeln(
          '${contact.name} (${contact.relationship}) - ${contact.phoneNumber}',
        );
      }
    }

    buffer.write(
      '--------------------------------\nGenerated by MedAlert Nepal',
    );
    return buffer.toString();
  }

  /// Whether [data] actually fits in a QR code at the settings below.
  ///
  /// Necessary because QrImageView's own `errorStateBuilder` never fires for
  /// this case: QrValidator.validate reports oversized input as *valid*
  /// (qr 3.0.2 builds the code lazily, so nothing has counted the bits yet),
  /// and the InputTooLongException is thrown later from QrPainter during
  /// paint -- past the point the builder covers, so it takes the tab down.
  /// Building a QrImage from the code here forces that work to happen where
  /// it can be caught -- that is the step that actually fills the bit buffer
  /// and compares it against the version's capacity.
  bool _fitsInQrCode(String data) {
    try {
      QrImage(
        QrCode.fromData(data: data, errorCorrectLevel: QrErrorCorrectLevel.M),
      );
      return true;
    } catch (_) {
      return false;
    }
  }

  /// Shown in place of the QR when the profile no longer fits in one.
  ///
  /// Sized to match the QR it replaces so the card does not jump, and worded
  /// as an instruction rather than an error because the fix is entirely in
  /// the user's hands: shorten the medication or allergy text, or remove an
  /// emergency contact.
  Widget _qrTooLong(BuildContext context) {
    return SizedBox(
      width: 160,
      height: 160,
      child: Padding(
        padding: const EdgeInsets.all(8),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(
              Icons.qr_code_2_outlined,
              size: 28,
              color: Colors.black54,
            ),
            const SizedBox(height: 6),
            // Flexible so the message shrinks into the QR's footprint instead
            // of overflowing it -- the surrounding card is a fixed 160px and
            // an overflow stripe here would look like a rendering bug on a
            // screen a responder is meant to trust.
            Flexible(
              child: Text(
                'Profile too long for an offline QR code. Shorten your '
                'medications or allergies.',
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                  color: Colors.black87,
                  fontSize: 10,
                  height: 1.25,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// The rectangle iPad anchors the share popover to: the QR code itself, in
  /// global coordinates, so the sheet points at the thing being shared.
  ///
  /// Falls back to the centre of the screen when the boundary has gone (a
  /// rebuild mid-share), and to a 1x1 rect at the origin when even that is
  /// unavailable -- an arbitrary but valid anchor beats throwing, because on
  /// iPhone and Android the value is ignored entirely.
  Rect _shareOrigin() {
    final box = _qrBoundaryKey.currentContext?.findRenderObject() as RenderBox?;
    if (box != null && box.hasSize) {
      return box.localToGlobal(Offset.zero) & box.size;
    }
    final size = MediaQuery.maybeOf(context)?.size;
    if (size != null) {
      return Rect.fromCenter(
        center: Offset(size.width / 2, size.height / 2),
        width: 1,
        height: 1,
      );
    }
    return const Rect.fromLTWH(0, 0, 1, 1);
  }

  Future<void> _downloadQrCode(UserProfile profile) async {
    if (_isDownloading) return;
    setState(() => _isDownloading = true);

    try {
      final boundary =
          _qrBoundaryKey.currentContext?.findRenderObject()
              as RenderRepaintBoundary?;
      if (boundary == null) {
        throw Exception('QR code is not ready yet');
      }

      final image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) {
        throw Exception('Could not encode QR code image');
      }
      final bytes = byteData.buffer.asUint8List();

      final xFile = XFile.fromData(
        bytes,
        name: 'medalert_medical_id_qr.png',
        mimeType: 'image/png',
      );

      if (!mounted) return;
      await Share.shareXFiles(
        [xFile],
        text: 'My MedAlert emergency medical ID',
        // Required on iPad, where the share sheet is a popover that UIKit
        // anchors to a rectangle instead of sliding up from the bottom.
        // Omitting it throws PlatformException(sharePositionOrigin), which
        // this screen then reported as "could not generate QR code" -- the
        // image was fine, only the sheet failed to open.
        sharePositionOrigin: _shareOrigin(),
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          // The QR is rendered and encoded before we get here, so a failure
          // at this point is the share sheet, not the code itself. Saying
          // "could not generate" sent us looking in the wrong place.
          SnackBar(content: Text('Could not share the QR code: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isDownloading = false);
    }
  }

  String _display(String value, [String fallback = 'Not set']) {
    final t = value.trim();
    return t.isEmpty ? fallback : t;
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final state = AppStateManager.instance;
    final bg = isDark ? const Color(0xFF111418) : const Color(0xFFF0F2F7);

    // No nested Scaffold — this screen is already inside AppShell's Scaffold.
    // Using another Scaffold + SafeArea was eating space and hiding content.
    return ColoredBox(
      color: bg,
      child: ValueListenableBuilder<UserProfile>(
        valueListenable: state.userProfileNotifier,
        builder: (context, profile, _) {
          return LayoutBuilder(
            builder: (context, constraints) {
              final isWide = constraints.maxWidth >= 720;
              final hPad = isWide ? 28.0 : 14.0;

              return SingleChildScrollView(
                padding: EdgeInsets.fromLTRB(hPad, 12, hPad, 100),
                child: isWide
                    ? _buildWideLayout(context, profile, isDark)
                    : _buildPhoneLayout(context, profile, isDark),
              );
            },
          );
        },
      ),
    );
  }

  Widget _buildPhoneLayout(
    BuildContext context,
    UserProfile profile,
    bool isDark,
  ) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        _buildIdCard(context, profile, isDark),
        const SizedBox(height: 12),
        _buildQuickStats(context, profile, isDark),
        const SizedBox(height: 12),
        _buildQRSection(context, profile, isDark),
        const SizedBox(height: 12),
        _buildAllergiesSection(context, profile.allergies, isDark),
        const SizedBox(height: 12),
        _buildMedicationsSection(context, profile.medications, isDark),
        const SizedBox(height: 12),
        _buildContactsSection(context, profile.emergencyContacts, isDark),
        const SizedBox(height: 12),
        _buildDetailsSection(context, profile, isDark),
      ],
    );
  }

  Widget _buildWideLayout(
    BuildContext context,
    UserProfile profile,
    bool isDark,
  ) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(
          flex: 5,
          child: Column(
            children: [
              _buildIdCard(context, profile, isDark),
              const SizedBox(height: 14),
              _buildQRSection(context, profile, isDark),
            ],
          ),
        ),
        const SizedBox(width: 16),
        Expanded(
          flex: 6,
          child: Column(
            children: [
              _buildQuickStats(context, profile, isDark),
              const SizedBox(height: 14),
              _buildAllergiesSection(context, profile.allergies, isDark),
              const SizedBox(height: 14),
              _buildMedicationsSection(context, profile.medications, isDark),
              const SizedBox(height: 14),
              _buildContactsSection(context, profile.emergencyContacts, isDark),
              const SizedBox(height: 14),
              _buildDetailsSection(context, profile, isDark),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildIdCard(BuildContext context, UserProfile profile, bool isDark) {
    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20),
        gradient: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFF003D7A), Color(0xFF005AB4), Color(0xFF0A73E0)],
        ),
        boxShadow: [
          BoxShadow(
            color: const Color(0xFF005AB4).withValues(alpha: 0.35),
            blurRadius: 20,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Stack(
        children: [
          Positioned(
            right: -30,
            top: -30,
            child: Container(
              width: 120,
              height: 120,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: Colors.white.withValues(alpha: 0.06),
              ),
            ),
          ),
          Positioned(
            right: 40,
            bottom: -40,
            child: Container(
              width: 100,
              height: 100,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: Colors.white.withValues(alpha: 0.05),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(18, 16, 14, 18),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 3,
                      ),
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.15),
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: const Text(
                        'MEDALERT  ·  MEDICAL ID',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 10,
                          fontWeight: FontWeight.w800,
                          letterSpacing: 0.8,
                        ),
                      ),
                    ),
                    const Spacer(),
                    Material(
                      color: Colors.white.withValues(alpha: 0.15),
                      borderRadius: BorderRadius.circular(10),
                      child: InkWell(
                        borderRadius: BorderRadius.circular(10),
                        onTap: () =>
                            Navigator.pushNamed(context, '/edit_medical_id'),
                        child: const Padding(
                          padding: EdgeInsets.all(8),
                          child: Icon(
                            Icons.edit_outlined,
                            color: Colors.white,
                            size: 18,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(2.5),
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        border: Border.all(
                          color: Colors.white.withValues(alpha: 0.45),
                          width: 2,
                        ),
                      ),
                      child: InitialsAvatar(
                        name: profile.fullName.isNotEmpty
                            ? profile.fullName
                            : 'U',
                        imageUrl: profile.profilePictureUrl,
                        radius: 28,
                      ),
                    ),
                    const SizedBox(width: 14),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            profile.fullName.isNotEmpty
                                ? profile.fullName
                                : 'Your Name',
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 19,
                              fontWeight: FontWeight.w800,
                              letterSpacing: -0.3,
                              height: 1.2,
                            ),
                            maxLines: 2,
                            overflow: TextOverflow.ellipsis,
                          ),
                          const SizedBox(height: 4),
                          Text(
                            () {
                              final parts = <String>[];
                              if (profile.gender.isNotEmpty) {
                                parts.add(profile.gender);
                              }
                              if (profile.dob.isNotEmpty) {
                                parts.add(profile.dob);
                              }
                              return parts.isEmpty
                                  ? 'Complete your profile'
                                  : parts.join('  ·  ');
                            }(),
                            style: TextStyle(
                              color: Colors.white.withValues(alpha: 0.8),
                              fontSize: 12.5,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 12,
                          vertical: 8,
                        ),
                        decoration: BoxDecoration(
                          color: Colors.white.withValues(alpha: 0.12),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'MEDICAL ID',
                              style: TextStyle(
                                color: Colors.white.withValues(alpha: 0.65),
                                fontSize: 9,
                                fontWeight: FontWeight.w700,
                                letterSpacing: 0.8,
                              ),
                            ),
                            const SizedBox(height: 2),
                            Text(
                              profile.medicalId.isNotEmpty
                                  ? profile.medicalId
                                  : '—',
                              style: const TextStyle(
                                color: Colors.white,
                                fontSize: 14,
                                fontWeight: FontWeight.w800,
                                letterSpacing: 0.3,
                              ),
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(width: 10),
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 14,
                        vertical: 8,
                      ),
                      decoration: BoxDecoration(
                        color: const Color(0xFFBA1A1A),
                        borderRadius: BorderRadius.circular(10),
                        boxShadow: [
                          BoxShadow(
                            color: const Color(
                              0xFFBA1A1A,
                            ).withValues(alpha: 0.4),
                            blurRadius: 8,
                            offset: const Offset(0, 3),
                          ),
                        ],
                      ),
                      child: Column(
                        children: [
                          Text(
                            'BLOOD',
                            style: TextStyle(
                              color: Colors.white.withValues(alpha: 0.8),
                              fontSize: 9,
                              fontWeight: FontWeight.w700,
                              letterSpacing: 0.8,
                            ),
                          ),
                          const SizedBox(height: 1),
                          Text(
                            profile.bloodGroup.isNotEmpty
                                ? profile.bloodGroup
                                : '—',
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 18,
                              fontWeight: FontWeight.w900,
                              height: 1.15,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildQuickStats(
    BuildContext context,
    UserProfile profile,
    bool isDark,
  ) {
    return Row(
      children: [
        Expanded(
          child: _statChip(
            context,
            isDark,
            icon: Icons.height_rounded,
            label: 'Height',
            value: profile.height.isNotEmpty ? '${profile.height} cm' : '—',
            color: const Color(0xFF0A73E0),
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: _statChip(
            context,
            isDark,
            icon: Icons.monitor_weight_outlined,
            label: 'Weight',
            value: profile.weight.isNotEmpty ? '${profile.weight} kg' : '—',
            color: const Color(0xFF0D9B6B),
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: _statChip(
            context,
            isDark,
            icon: Icons.phone_outlined,
            label: 'Phone',
            value: profile.phoneNumber.isNotEmpty ? profile.phoneNumber : '—',
            color: const Color(0xFF7C4DFF),
            smallValue: true,
          ),
        ),
      ],
    );
  }

  Widget _statChip(
    BuildContext context,
    bool isDark, {
    required IconData icon,
    required String label,
    required String value,
    required Color color,
    bool smallValue = false,
  }) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 12),
      decoration: _cardDeco(isDark),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, size: 18, color: color),
          const SizedBox(height: 8),
          Text(
            label,
            style: TextStyle(
              fontSize: 10,
              fontWeight: FontWeight.w600,
              color: isDark ? Colors.white54 : Colors.black45,
            ),
          ),
          const SizedBox(height: 2),
          Text(
            value,
            style: TextStyle(
              fontSize: smallValue ? 11 : 14,
              fontWeight: FontWeight.w800,
              color: isDark ? Colors.white : Colors.black87,
              height: 1.2,
            ),
            maxLines: 2,
            overflow: TextOverflow.ellipsis,
          ),
        ],
      ),
    );
  }

  Widget _buildQRSection(
    BuildContext context,
    UserProfile profile,
    bool isDark,
  ) {
    final theme = Theme.of(context);
    // Encoded once per build and shared by the code itself and the download
    // button below, so the payload is not built and bit-packed three times
    // on every rebuild of this card.
    final payload = _buildEmergencyPayload(profile);
    final fitsInQr = _fitsInQrCode(payload);
    return Container(
      decoration: _cardDeco(isDark),
      padding: const EdgeInsets.all(16),
      child: Column(
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: const Color(0xFFBA1A1A).withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: const Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.emergency, size: 12, color: Color(0xFFBA1A1A)),
                    SizedBox(width: 4),
                    Text(
                      'EMERGENCY QR',
                      style: TextStyle(
                        fontSize: 10,
                        fontWeight: FontWeight.w800,
                        color: Color(0xFFBA1A1A),
                        letterSpacing: 0.5,
                      ),
                    ),
                  ],
                ),
              ),
              const Spacer(),
              Text(
                'Scan offline',
                style: TextStyle(
                  fontSize: 11,
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),
          RepaintBoundary(
            key: _qrBoundaryKey,
            child: Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(14),
                border: Border.all(color: const Color(0xFFE5E9F0)),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.05),
                    blurRadius: 12,
                    offset: const Offset(0, 4),
                  ),
                ],
              ),
              child: !fitsInQr
                  ? _qrTooLong(context)
                  : QrImageView(
                      data: payload,
                      version: QrVersions.auto,
                      errorCorrectionLevel: QrErrorCorrectLevel.M,
                      size: 160,
                      backgroundColor: Colors.white,
                      // A QR code tops out around 2.3 KB at this correction level,
                      // and the payload grows with every allergy, medication and
                      // emergency contact -- none of which the editor caps. Without
                      // this builder qr_flutter throws QrInputTooLongException
                      // during build, which takes down the whole Medical ID tab.
                      //
                      // Deliberately not truncating the payload to make it fit: a
                      // silently dropped allergy is exactly the failure this screen
                      // exists to prevent. Better to show nothing and say why, so
                      // the user shortens it themselves.
                      // Kept as a second line of defence for the other failure
                      // modes validate() does catch.
                      errorStateBuilder: (context, _) => _qrTooLong(context),
                    ),
            ),
          ),
          const SizedBox(height: 10),
          Text(
            'ID · vitals · allergies · meds · contacts',
            style: TextStyle(
              fontSize: 11,
              color: theme.colorScheme.onSurfaceVariant,
              fontStyle: FontStyle.italic,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 12),
          SizedBox(
            width: double.infinity,
            height: 42,
            child: OutlinedButton.icon(
              // Disabled when there is no code to share: the repaint boundary
              // would otherwise capture the "too long" message and hand the
              // user a PNG of an error notice.
              onPressed: _isDownloading || !fitsInQr
                  ? null
                  : () => _downloadQrCode(profile),
              icon: _isDownloading
                  ? SizedBox(
                      width: 15,
                      height: 15,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: theme.colorScheme.primary,
                      ),
                    )
                  : const Icon(Icons.download_rounded, size: 17),
              label: Text(
                _isDownloading ? 'Preparing…' : 'Download QR',
                style: const TextStyle(
                  fontWeight: FontWeight.w700,
                  fontSize: 13,
                ),
              ),
              style: OutlinedButton.styleFrom(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(11),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildAllergiesSection(
    BuildContext context,
    List<String> allergies,
    bool isDark,
  ) {
    final theme = Theme.of(context);
    final hasAllergies = allergies.isNotEmpty;

    return Container(
      decoration: _cardDeco(
        isDark,
        borderColor: hasAllergies
            ? const Color(0xFFBA1A1A).withValues(alpha: 0.3)
            : null,
      ),
      padding: const EdgeInsets.all(14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionHeader(
            Icons.warning_amber_rounded,
            'Severe Allergies',
            const Color(0xFFBA1A1A),
            trailing: hasAllergies
                ? Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 7,
                      vertical: 2,
                    ),
                    decoration: BoxDecoration(
                      color: const Color(0xFFBA1A1A),
                      borderRadius: BorderRadius.circular(10),
                    ),
                    child: Text(
                      '${allergies.length}',
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 11,
                        fontWeight: FontWeight.w800,
                      ),
                    ),
                  )
                : null,
          ),
          const SizedBox(height: 12),
          if (!hasAllergies)
            Text(
              'No known severe allergies',
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.outline,
              ),
            )
          else
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: allergies.map((a) {
                return Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 7,
                  ),
                  decoration: BoxDecoration(
                    color: const Color(0xFFBA1A1A).withValues(alpha: 0.1),
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                      color: const Color(0xFFBA1A1A).withValues(alpha: 0.25),
                    ),
                  ),
                  child: Text(
                    a,
                    style: const TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w700,
                      color: Color(0xFFBA1A1A),
                    ),
                  ),
                );
              }).toList(),
            ),
        ],
      ),
    );
  }

  Widget _buildMedicationsSection(
    BuildContext context,
    List<Medication> medications,
    bool isDark,
  ) {
    final theme = Theme.of(context);

    return Container(
      decoration: _cardDeco(isDark),
      padding: const EdgeInsets.all(14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionHeader(
            Icons.medication_outlined,
            'Current Medications',
            theme.colorScheme.primary,
            trailing: medications.isNotEmpty
                ? Text(
                    '${medications.length}',
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w700,
                      color: theme.colorScheme.onSurfaceVariant,
                    ),
                  )
                : null,
          ),
          const SizedBox(height: 12),
          if (medications.isEmpty)
            Text(
              'No current medications',
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.outline,
              ),
            )
          else
            ...medications.asMap().entries.map((entry) {
              final i = entry.key;
              final med = entry.value;
              return Column(
                children: [
                  if (i > 0)
                    Divider(
                      height: 16,
                      color: theme.colorScheme.outlineVariant.withValues(
                        alpha: 0.25,
                      ),
                    ),
                  Row(
                    children: [
                      Container(
                        width: 38,
                        height: 38,
                        decoration: BoxDecoration(
                          color: theme.colorScheme.primary.withValues(
                            alpha: 0.1,
                          ),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: Icon(
                          Icons.medication,
                          size: 18,
                          color: theme.colorScheme.primary,
                        ),
                      ),
                      const SizedBox(width: 11),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              med.name,
                              style: const TextStyle(
                                fontWeight: FontWeight.w700,
                                fontSize: 14,
                              ),
                            ),
                            if (med.frequency.isNotEmpty)
                              Text(
                                med.frequency,
                                style: TextStyle(
                                  fontSize: 12,
                                  color: theme.colorScheme.onSurfaceVariant,
                                ),
                              ),
                          ],
                        ),
                      ),
                      if (med.dosage.isNotEmpty)
                        Container(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 9,
                            vertical: 4,
                          ),
                          decoration: BoxDecoration(
                            color: theme.colorScheme.primary.withValues(
                              alpha: 0.1,
                            ),
                            borderRadius: BorderRadius.circular(7),
                          ),
                          child: Text(
                            med.dosage,
                            style: TextStyle(
                              fontWeight: FontWeight.w800,
                              fontSize: 12,
                              color: theme.colorScheme.primary,
                            ),
                          ),
                        ),
                    ],
                  ),
                ],
              );
            }),
        ],
      ),
    );
  }

  Widget _buildContactsSection(
    BuildContext context,
    List<EmergencyContact> contacts,
    bool isDark,
  ) {
    final theme = Theme.of(context);

    return Container(
      decoration: _cardDeco(isDark),
      padding: const EdgeInsets.all(14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionHeader(
            Icons.groups_outlined,
            'Emergency Contacts',
            theme.colorScheme.primary,
          ),
          const SizedBox(height: 12),
          if (contacts.isEmpty)
            Text(
              'No emergency contacts added',
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.outline,
              ),
            )
          else
            ...contacts.map((contact) {
              return Container(
                margin: const EdgeInsets.only(bottom: 8),
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: isDark
                      ? const Color(0xFF15181C)
                      : const Color(0xFFF4F6FA),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Row(
                  children: [
                    CircleAvatar(
                      radius: 20,
                      backgroundColor: theme.colorScheme.primary.withValues(
                        alpha: 0.12,
                      ),
                      child: contact.initials != null
                          ? Text(
                              contact.initials!,
                              style: TextStyle(
                                color: theme.colorScheme.primary,
                                fontWeight: FontWeight.w800,
                                fontSize: 12,
                              ),
                            )
                          : Icon(
                              Icons.person,
                              color: theme.colorScheme.primary,
                              size: 18,
                            ),
                    ),
                    const SizedBox(width: 11),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            contact.name,
                            style: const TextStyle(
                              fontWeight: FontWeight.w700,
                              fontSize: 14,
                            ),
                          ),
                          Text(
                            contact.relationship,
                            style: TextStyle(
                              fontSize: 12,
                              color: theme.colorScheme.onSurfaceVariant,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Material(
                      color: const Color(0xFF0D9B6B).withValues(alpha: 0.12),
                      borderRadius: BorderRadius.circular(10),
                      child: InkWell(
                        borderRadius: BorderRadius.circular(10),
                        onTap: contact.phoneNumber.trim().isEmpty
                            ? null
                            : () => dialEmergencyNumber(
                                context,
                                contact.phoneNumber,
                                subject:
                                    '${contact.name} (${contact.relationship})',
                              ),
                        child: const Padding(
                          padding: EdgeInsets.all(9),
                          child: Icon(
                            Icons.call_rounded,
                            color: Color(0xFF0D9B6B),
                            size: 18,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              );
            }),
        ],
      ),
    );
  }

  Widget _buildDetailsSection(
    BuildContext context,
    UserProfile profile,
    bool isDark,
  ) {
    final theme = Theme.of(context);
    final rows = <(IconData, String, String)>[
      (Icons.phone_outlined, 'Phone', _display(profile.phoneNumber)),
      (Icons.cake_outlined, 'Date of Birth', _display(profile.dob)),
      (Icons.person_outline, 'Gender', _display(profile.gender)),
      (Icons.location_on_outlined, 'Address', _display(profile.address)),
      (Icons.badge_outlined, 'Medical ID', _display(profile.medicalId)),
      (Icons.water_drop_outlined, 'Blood Group', _display(profile.bloodGroup)),
    ];

    return Container(
      decoration: _cardDeco(isDark),
      padding: const EdgeInsets.all(14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionHeader(
            Icons.info_outline,
            'Full Profile',
            theme.colorScheme.primary,
          ),
          const SizedBox(height: 10),
          ...rows.asMap().entries.map((entry) {
            final i = entry.key;
            final (icon, label, value) = entry.value;
            return Column(
              children: [
                if (i > 0)
                  Divider(
                    height: 14,
                    color: theme.colorScheme.outlineVariant.withValues(
                      alpha: 0.2,
                    ),
                  ),
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 4),
                  child: Row(
                    children: [
                      Icon(icon, size: 16, color: theme.colorScheme.primary),
                      const SizedBox(width: 10),
                      SizedBox(
                        width: 100,
                        child: Text(
                          label,
                          style: TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.w600,
                            color: theme.colorScheme.onSurfaceVariant,
                          ),
                        ),
                      ),
                      Expanded(
                        child: Text(
                          value,
                          style: const TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w600,
                          ),
                          textAlign: TextAlign.right,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            );
          }),
        ],
      ),
    );
  }

  BoxDecoration _cardDeco(bool isDark, {Color? borderColor}) {
    return BoxDecoration(
      color: isDark ? const Color(0xFF1D2024) : Colors.white,
      borderRadius: BorderRadius.circular(16),
      border: Border.all(
        color:
            borderColor ??
            (isDark
                ? Colors.white.withValues(alpha: 0.06)
                : const Color(0xFFE6EAF0)),
      ),
      boxShadow: isDark
          ? null
          : [
              BoxShadow(
                color: Colors.black.withValues(alpha: 0.04),
                blurRadius: 10,
                offset: const Offset(0, 3),
              ),
            ],
    );
  }

  Widget _sectionHeader(
    IconData icon,
    String title,
    Color color, {
    Widget? trailing,
  }) {
    return Row(
      children: [
        Container(
          width: 28,
          height: 28,
          decoration: BoxDecoration(
            color: color.withValues(alpha: 0.12),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Icon(icon, size: 15, color: color),
        ),
        const SizedBox(width: 9),
        Expanded(
          child: Text(
            title,
            style: const TextStyle(
              fontWeight: FontWeight.w800,
              fontSize: 14.5,
              letterSpacing: -0.2,
            ),
          ),
        ),
        ?trailing,
      ],
    );
  }
}
