import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';
import 'package:cross_file/cross_file.dart';
import '../state.dart';
import '../widgets/initials_avatar.dart';

class MedicalIdScreen extends StatefulWidget {
  const MedicalIdScreen({super.key});

  @override
  State<MedicalIdScreen> createState() => _MedicalIdScreenState();
}

class _MedicalIdScreenState extends State<MedicalIdScreen> {
  final GlobalKey _qrBoundaryKey = GlobalKey();
  bool _isDownloading = false;

  /// Builds the plain-text payload encoded directly into the QR code.
  ///
  /// This is deliberately self-contained (not a link to a server) so a
  /// first responder can read it from any QR scanner, offline, with no
  /// dependency on the app or network access at the scene.
  String _buildEmergencyPayload(UserProfile profile) {
    final buffer = StringBuffer()
      ..writeln('MEDALERT EMERGENCY MEDICAL ID')
      ..writeln('--------------------------------')
      ..writeln('Name: ${profile.fullName}')
      ..writeln('Blood Group: ${profile.bloodGroup.isNotEmpty ? profile.bloodGroup : 'Not specified'}')
      ..writeln('DOB: ${profile.dob}');

    if (profile.address.trim().isNotEmpty) {
      buffer.writeln('Address: ${profile.address}');
    }

    buffer.writeln(
      'Allergies: ${profile.allergies.isEmpty ? 'None reported' : profile.allergies.join(', ')}',
    );

    if (profile.medications.isNotEmpty) {
      final meds = profile.medications
          .map((m) => '${m.name} ${m.dosage} (${m.frequency})')
          .join('; ');
      buffer.writeln('Medications: $meds');
    }

    if (profile.emergencyContacts.isNotEmpty) {
      buffer.writeln('--------------------------------');
      buffer.writeln('Emergency Contacts:');
      for (final contact in profile.emergencyContacts) {
        buffer.writeln('${contact.name} (${contact.relationship}) - ${contact.phoneNumber}');
      }
    }

    buffer.write('--------------------------------\nGenerated by MedAlert Nepal');
    return buffer.toString();
  }

  Future<void> _downloadQrCode(UserProfile profile) async {
    if (_isDownloading) return;
    setState(() => _isDownloading = true);

    try {
      final boundary =
          _qrBoundaryKey.currentContext?.findRenderObject() as RenderRepaintBoundary?;
      if (boundary == null) {
        throw Exception('QR code is not ready yet');
      }

      // Render at a high pixel ratio so the downloaded image stays sharp
      // and scannable even when zoomed in or printed.
      final image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) {
        throw Exception('Could not encode QR code image');
      }
      final bytes = byteData.buffer.asUint8List();

      // Built from in-memory bytes rather than a written file, so this
      // works the same way on mobile, desktop, and web.
      final xFile = XFile.fromData(
        bytes,
        name: 'medalert_medical_id_qr.png',
        mimeType: 'image/png',
      );

      if (!mounted) return;
      await Share.shareXFiles(
        [xFile],
        text: 'My MedAlert emergency medical ID',
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Could not generate QR code: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isDownloading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final state = AppStateManager.instance;

    return Scaffold(
      body: ValueListenableBuilder<UserProfile>(
        valueListenable: state.userProfileNotifier,
        builder: (context, profile, _) {
          return SingleChildScrollView(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Profile Header
                Row(
                  children: [
                    Stack(
                      children: [
                        Container(
                          width: 80,
                          height: 80,
                          padding: const EdgeInsets.all(2),
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            border: Border.all(
                              color: theme.colorScheme.primaryContainer.withOpacity(0.5),
                              width: 2,
                            ),
                          ),
                          child: InitialsAvatar(
                            name: profile.fullName,
                            imageUrl: profile.profilePictureUrl,
                            radius: 38,
                          ),
                        ),
                        Positioned(
                          bottom: 0,
                          right: 0,
                          child: Container(
                            width: 20,
                            height: 20,
                            decoration: BoxDecoration(
                              color: isDark ? const Color(0xFFFFB68C) : theme.colorScheme.tertiary,
                              shape: BoxShape.circle,
                              border: Border.all(
                                color: isDark ? Colors.black : Colors.white,
                                width: 2,
                              ),
                            ),
                            child: const Icon(
                              Icons.check,
                              size: 12,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            profile.fullName,
                            style: theme.textTheme.titleLarge?.copyWith(
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Text(
                            '${profile.gender} • ${profile.dob}',
                            style: theme.textTheme.bodyMedium?.copyWith(
                              color: theme.colorScheme.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 6),
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                            decoration: BoxDecoration(
                              color: theme.colorScheme.surfaceContainerHighest,
                              borderRadius: BorderRadius.circular(6),
                            ),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Icon(
                                  Icons.monitor_heart,
                                  size: 14,
                                  color: theme.colorScheme.primary,
                                ),
                                const SizedBox(width: 4),
                                Text(
                                  'ID: ${profile.medicalId}',
                                  style: theme.textTheme.bodySmall?.copyWith(
                                    fontWeight: FontWeight.bold,
                                    color: theme.colorScheme.onSurfaceVariant,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.edit),
                      onPressed: () {
                        Navigator.pushNamed(context, '/edit_medical_id');
                      },
                      style: IconButton.styleFrom(
                        backgroundColor: theme.colorScheme.primaryContainer.withOpacity(0.1),
                        foregroundColor: theme.colorScheme.primary,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 24),

                // Bento Grid
                LayoutBuilder(
                  builder: (context, constraints) {
                    if (constraints.maxWidth > 650) {
                      return Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Expanded(
                            flex: 5,
                            child: _buildQRCard(context, profile),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            flex: 7,
                            child: Column(
                              children: [
                                _buildVitalsGrid(context, profile),
                                const SizedBox(height: 16),
                                _buildAllergiesCard(context, profile.allergies),
                                const SizedBox(height: 16),
                                _buildMedicationsCard(context, profile.medications),
                              ],
                            ),
                          ),
                        ],
                      );
                    } else {
                      return Column(
                        children: [
                          _buildQRCard(context, profile),
                          const SizedBox(height: 16),
                          _buildVitalsGrid(context, profile),
                          const SizedBox(height: 16),
                          _buildAllergiesCard(context, profile.allergies),
                          const SizedBox(height: 16),
                          _buildMedicationsCard(context, profile.medications),
                        ],
                      );
                    }
                  },
                ),
                const SizedBox(height: 16),

                // Emergency Contacts
                _buildEmergencyContactsCard(context, profile.emergencyContacts),
                const SizedBox(height: 80), // bottom margin
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _buildQRCard(BuildContext context, UserProfile profile) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1D2024) : Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: theme.colorScheme.outlineVariant.withOpacity(0.3),
        ),
        boxShadow: const [BoxShadow(color: Colors.black12, blurRadius: 4)],
      ),
      padding: const EdgeInsets.all(24.0),
      child: Column(
        children: [
          Text(
            'Responder Scan',
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Scan for instant access to critical medical history.',
            style: theme.textTheme.bodySmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 24),
          RepaintBoundary(
            key: _qrBoundaryKey,
            child: Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: theme.colorScheme.outlineVariant.withOpacity(0.5),
                ),
              ),
              child: QrImageView(
                data: _buildEmergencyPayload(profile),
                version: QrVersions.auto,
                errorCorrectionLevel: QrErrorCorrectLevel.M,
                size: 180,
                backgroundColor: Colors.white,
              ),
            ),
          ),
          const SizedBox(height: 12),
          Text(
            'Contains name, blood group, address, allergies & emergency contacts',
            style: theme.textTheme.bodySmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
              fontStyle: FontStyle.italic,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 24),
          OutlinedButton.icon(
            onPressed: _isDownloading ? null : () => _downloadQrCode(profile),
            icon: _isDownloading
                ? SizedBox(
                    width: 16,
                    height: 16,
                    child: CircularProgressIndicator(
                      strokeWidth: 2,
                      color: theme.colorScheme.primary,
                    ),
                  )
                : const Icon(Icons.download),
            label: Text(
              _isDownloading ? 'Preparing...' : 'Download QR Code',
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            style: OutlinedButton.styleFrom(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildVitalsGrid(BuildContext context, UserProfile profile) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return GridView.count(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      crossAxisCount: 3,
      crossAxisSpacing: 12,
      childAspectRatio: 0.9,
      children: [
        // Blood Group
        Container(
          decoration: BoxDecoration(
            color: const Color(0xFFFFDAD6).withOpacity(0.3),
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: const Color(0xFFBA1A1A).withOpacity(0.2),
            ),
          ),
          padding: const EdgeInsets.all(12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Row(
                children: [
                  Icon(Icons.water_drop, color: Color(0xFFBA1A1A), size: 18),
                  SizedBox(width: 4),
                  Text(
                    'Blood Group',
                    style: TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFFBA1A1A),
                    ),
                  ),
                ],
              ),
              Text(
                profile.bloodGroup,
                style: const TextStyle(
                  fontSize: 32,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFFBA1A1A),
                  letterSpacing: -1,
                ),
              ),
            ],
          ),
        ),
        // Height
        Container(
          decoration: BoxDecoration(
            color: isDark ? const Color(0xFF1D2024) : Colors.white,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: theme.colorScheme.outlineVariant.withOpacity(0.3),
            ),
          ),
          padding: const EdgeInsets.all(12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  Icon(Icons.height, color: theme.colorScheme.secondary, size: 18),
                  const SizedBox(width: 4),
                  Text(
                    'Height',
                    style: TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                      color: theme.colorScheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ),
              Text(
                profile.height,
                style: theme.textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                  fontSize: 22,
                ),
              ),
            ],
          ),
        ),
        // Weight
        Container(
          decoration: BoxDecoration(
            color: isDark ? const Color(0xFF1D2024) : Colors.white,
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: theme.colorScheme.outlineVariant.withOpacity(0.3),
            ),
          ),
          padding: const EdgeInsets.all(12),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  Icon(Icons.scale, color: theme.colorScheme.secondary, size: 18),
                  const SizedBox(width: 4),
                  Text(
                    'Weight',
                    style: TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                      color: theme.colorScheme.onSurfaceVariant,
                    ),
                  ),
                ],
              ),
              RichText(
                text: TextSpan(
                  children: [
                    TextSpan(
                      text: profile.weight,
                      style: theme.textTheme.headlineMedium?.copyWith(
                        fontWeight: FontWeight.bold,
                        fontSize: 22,
                        color: theme.colorScheme.onSurface,
                      ),
                    ),
                    TextSpan(
                      text: ' lbs',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildAllergiesCard(BuildContext context, List<String> allergies) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1D2024) : Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: theme.colorScheme.outlineVariant.withOpacity(0.3),
        ),
      ),
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.warning, color: Color(0xFFBA1A1A), size: 20),
              const SizedBox(width: 8),
              Text(
                'Severe Allergies',
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          if (allergies.isEmpty)
            Text(
              'No known severe allergies.',
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.outline),
            )
          else
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: allergies.map((allergy) {
                return Container(
                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                  decoration: BoxDecoration(
                    color: const Color(0xFFBA1A1A).withOpacity(0.1),
                    borderRadius: BorderRadius.circular(99),
                    border: Border.all(
                      color: const Color(0xFFBA1A1A).withOpacity(0.2),
                    ),
                  ),
                  child: Text(
                    allergy,
                    style: const TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFFBA1A1A),
                    ),
                  ),
                );
              }).toList(),
            ),
        ],
      ),
    );
  }

  Widget _buildMedicationsCard(BuildContext context, List<Medication> medications) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1D2024) : Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: theme.colorScheme.outlineVariant.withOpacity(0.3),
        ),
      ),
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(Icons.medication, color: theme.colorScheme.primary, size: 20),
              const SizedBox(width: 8),
              Text(
                'Current Medications',
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          if (medications.isEmpty)
            Text(
              'No current medications.',
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.outline),
            )
          else
            Column(
              children: medications.map((med) {
                return Container(
                  decoration: BoxDecoration(
                    border: Border(
                      bottom: BorderSide(
                        color: theme.colorScheme.outlineVariant.withOpacity(0.2),
                      ),
                    ),
                  ),
                  padding: const EdgeInsets.symmetric(vertical: 8.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            med.name,
                            style: theme.textTheme.bodyMedium?.copyWith(
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          Text(
                            med.frequency,
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: theme.colorScheme.onSurfaceVariant,
                            ),
                          ),
                        ],
                      ),
                      Text(
                        med.dosage,
                        style: theme.textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                          color: theme.colorScheme.primary,
                        ),
                      ),
                    ],
                  ),
                );
              }).toList(),
            ),
        ],
      ),
    );
  }

  Widget _buildEmergencyContactsCard(BuildContext context, List<EmergencyContact> contacts) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1D2024) : Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: theme.colorScheme.outlineVariant.withOpacity(0.3),
        ),
      ),
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(Icons.group, color: theme.colorScheme.primary, size: 20),
              const SizedBox(width: 8),
              Text(
                'Emergency Contacts',
                style: theme.textTheme.titleMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          if (contacts.isEmpty)
            Text(
              'No emergency contacts added.',
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.outline),
            )
          else
            Column(
              children: contacts.map((contact) {
                return Container(
                  margin: const EdgeInsets.only(bottom: 12),
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: isDark ? const Color(0xFF15181C) : const Color(0xFFF9F9FF),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: theme.colorScheme.outlineVariant.withOpacity(0.2),
                    ),
                  ),
                  child: Row(
                    children: [
                      if (contact.initials != null)
                        CircleAvatar(
                          radius: 24,
                          backgroundColor: theme.colorScheme.secondaryContainer,
                          child: Text(
                            contact.initials!,
                            style: TextStyle(
                              color: theme.colorScheme.onSecondaryContainer,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        )
                      else
                        const CircleAvatar(
                          radius: 24,
                          backgroundColor: Colors.grey, // Default gray avatar
                          child: Icon(Icons.person, color: Colors.white), // Default person icon
                        ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              contact.name,
                              style: theme.textTheme.bodyMedium?.copyWith(
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            Text(
                              contact.relationship,
                              style: theme.textTheme.bodySmall?.copyWith(
                                color: theme.colorScheme.onSurfaceVariant,
                              ),
                            ),
                          ],
                        ),
                      ),
                      IconButton(
                        icon: const Icon(Icons.call),
                        onPressed: () {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(
                              content: Text('Calling ${contact.name}...'),
                              backgroundColor: theme.colorScheme.primary,
                            ),
                          );
                        },
                        style: IconButton.styleFrom(
                          backgroundColor: theme.colorScheme.primaryContainer,
                          foregroundColor: theme.colorScheme.onPrimaryContainer,
                        ),
                      ),
                    ],
                  ),
                );
              }).toList(),
            ),
        ],
      ),
    );
  }
}