# Generated by Django 6.0.7 on 2026-07-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSIntegrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='b51c5bf37d89c46dbe841cf99cc96ff412739ac3be1ca064e376f041efb2e21b', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_integration', to='pharmacy.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('DISPENSED', 'Dispensed'), ('RESTOCKED', 'Restocked'), ('ADJUSTED', 'Adjusted')], max_length=20)),
                ('source', models.CharField(choices=[('POS_SYNC', 'POS Sync'), ('MANUAL', 'Manual')], max_length=20)),
                ('client_timestamp', models.DateTimeField()),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='pharmacy.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='pharmacy.pharmacy')),
            ],
            options={
                'ordering': ['-server_timestamp'],
            },
        ),
    ]
