# Generated by Django 6.0.7 on 2026-07-25 08:28

import sync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posintegrationkey',
            name='key',
            field=models.CharField(default=sync.models.generate_pos_key, max_length=64, unique=True),
        ),
    ]
