# Generated by Django 6.0.7 on 2026-07-12 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('ngo', 'NGO')], max_length=20)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('is_24_hour', models.BooleanField(default=False)),
                ('has_icu', models.BooleanField(default=False)),
                ('has_oxygen', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('operating_hours', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Blood banks',
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('level', models.CharField(choices=[('adequate', 'Adequate'), ('low', 'Low'), ('critical', 'Critical'), ('unavailable', 'Unavailable')], max_length=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='emergency.bloodbank')),
            ],
            options={
                'verbose_name_plural': 'Blood stock',
                'unique_together': {('bank', 'blood_group')},
            },
        ),
    ]
